TEST_COMMAND=
EXE=
TOOLBASE = 
SRCONLY = 
HDRONLY = 
VERSION = 0.0.1
PATH_TO_BASE=../../..

# Makefile.testtool needs to define:
#   TEST_COMMAND - the commands to run under make test
#   EXE - executable built for this test.
#   TOOLBASE - the base filename for files with .h & .cpp versions
#   SRCONLY - any cpp files without headers.
#   HDRONLY - any header files without cpp
#   VERSION - if not 0.0.1
#   PATH_TO_BASE if it is not ../../..
include Makefile.testtool

include $(PATH_TO_BASE)/Makefile.include

#
# Goncalo's Generic Makefile -- Compiles and installs a Generic Goncalo Tool
# (c) 2000-2007 Goncalo Abecasis
#

# Source File Set
# For best results, consider editing this manually ...
TOOLHDR = $(TOOLBASE:=.h) $(HDRONLY)
TOOLSRC = $(TOOLBASE:=.cpp) $(SRCONLY)
TOOLOBJ = $(TOOLSRC:.cpp=.o)
LIBRARY = $(REQ_LIBS)
OBJECTS=$(patsubst %,$(OBJDIR)/%,$(TOOLOBJ))

# make everything
all : $(EXE)

# dependencies for executables
$(EXE) : $(LIBRARY) $(OBJECTS)
	$(CXX) $(CFLAGS) -o  $@ $(OBJECTS) $(LIBRARY) -lm -lz -lssl

$(OBJECTS): $(TOOLHDR) $(LIBHDR) | $(OBJDIR)

$(OBJDIR):
	mkdir $(OBJDIR)

clean :
	-rm -f $(OBJDIR)/*.o $(EXE) *~ results/*

test : all
	$(TEST_COMMAND)

$(OBJDIR)/%.o: %.c
	$(CXX) $(CFLAGS) -o $@ -c $*.c 

$(OBJDIR)/%.o: %.cpp 
	$(CXX) $(CFLAGS) -o $@ -c $*.cpp -DVERSION="\"$(VERSION)\""

.SUFFIXES : .cpp .c .o .X.o $(SUFFIXES)

DFLAGS=-Y

cleandepend:
	        makedepend -- $(DFLAGS) --

depend:
	        makedepend -- $(DFLAGS) -- $(TOOLSRC) >/dev/null 2>&1

# DO NOT DELETE THIS LINE -- make depend depends on it
