DIR_NAME=bam

TOOLBASE = ErrorHandler SamFileHeader SamFile GenericSamInterface SamInterface BamInterface SamRecord BamIndex SamHeaderHD SamHeaderPG SamHeaderRecord SamHeaderSQ SamHeaderRG SamHeaderTag SamValidation SamStatus SamFlag SamStatistics SamQuerySeqWithRefHelper SamFilter PileupReader PileupElement PileupElementBaseQual

HDRONLY = Pileup.h
